[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

